import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

companies = [
    {'No':1,'Company Name':'Maruti Techlabs','Specialization':'AI/ML, Deep Learning, Data Science','HR Email':'hr@marutitech.com','General Email':'contact@marutitech.com','Phone':'+91 9879101067','Website':'marutitech.com','Address':'10th Floor, The Ridge, Opp. Novotel, Iscon Char Rasta, Ahmedabad 380060','Careers URL':'marutitech.com/careers'},
    {'No':2,'Company Name':'Azilen Technologies','Specialization':'AI, Data, HRTech, Enterprise AI','HR Email':'hr@azilen.com','General Email':'info@azilen.com','Phone':'+91 79 4009 3121','Website':'azilen.com','Address':'12th & 13th Floor, B Square-1, Bopal-Ambli Road, Ahmedabad 380054','Careers URL':'azilen.com/careers'},
    {'No':3,'Company Name':'InFoCusp Innovations','Specialization':'AI, ML, Data Science, Computer Vision','HR Email':'hr@infocusp.com','General Email':'inquiries@infocusp.com','Phone':'N/A','Website':'infocusp.com','Address':'301-310, 4th Floor, Gala Hub, Gala Gymkhana Road, Bopal, Ahmedabad 380058','Careers URL':'infocusp.com/careers'},
    {'No':4,'Company Name':'Simform Solutions','Specialization':'AI/ML, Cloud, Data Engineering','HR Email':'hr@simformsolutions.com','General Email':'mitesh@simformsolutions.com','Phone':'N/A','Website':'simform.com','Address':'9th Floor, 901, BLOCK-A, KP Epitome, near Makarba, Ahmedabad 380051','Careers URL':'simformsolutions.freshteam.com/jobs'},
    {'No':5,'Company Name':'TechMayntra IT Solutions','Specialization':'AI/ML, Software Development','HR Email':'hr@techmayntra.com','General Email':'info@techmayntra.com','Phone':'+91 7984400506','Website':'techmayntra.com','Address':'915, J B Tower, Opp Doordarshan Kendra, Thaltej, Ahmedabad 380054','Careers URL':'techmayntra.com/careers'},
    {'No':6,'Company Name':'Spectrics Solutions','Specialization':'AI/ML Development, Data Science','HR Email':'hr@spectricssolutions.com','General Email':'info@spectricssolutions.com','Phone':'+91 9081431434','Website':'spectricssolutions.com','Address':'913, The Capital 2, Science City, Ahmedabad 380060','Careers URL':'spectricssolutions.com/careers'},
    {'No':7,'Company Name':'Technource','Specialization':'AI/ML, Python, Deep Learning, LLMs','HR Email':'hr@technource.com','General Email':'support@technource.com','Phone':'+91 9624770438','Website':'technource.com','Address':'Ahmedabad, Gujarat','Careers URL':'technource.com/careers'},
    {'No':8,'Company Name':'Hidden Brains Infotech','Specialization':'AI, ML, Big Data, Software Development','HR Email':'hr@hiddenbrains.com','General Email':'info@hiddenbrains.com','Phone':'+91 79 4000 0912','Website':'hiddenbrains.com','Address':'301, Sachet-4, Opp. Balaji Garden Restaurant, Satellite, Ahmedabad 380015','Careers URL':'hiddenbrains.com/careers'},
    {'No':9,'Company Name':'TatvaSoft','Specialization':'AI, Data Analytics, Custom Software','HR Email':'hr@tatvasoft.com','General Email':'info@tatvasoft.com','Phone':'+91 9601421472','Website':'tatvasoft.com','Address':'TatvaSoft House, Rajpath Club Road, Ahmedabad 380054','Careers URL':'tatvasoft.com/careers'},
    {'No':10,'Company Name':'Radixweb','Specialization':'AI, ML, Software Development, Cloud','HR Email':'hr@radixweb.com','General Email':'info@radixweb.com','Phone':'+91 9909003119','Website':'radixweb.com','Address':'Ekyarth, B/H Nirma University, Malabar County Road, Ahmedabad','Careers URL':'radixweb.com/careers'},
    {'No':11,'Company Name':'SoluLab','Specialization':'AI, Blockchain, ML, IoT','HR Email':'hr@solulab.com','General Email':'sales@solulab.com','Phone':'N/A','Website':'solulab.com','Address':'Ahmedabad, Gujarat','Careers URL':'solulab.com/careers'},
    {'No':12,'Company Name':'Vrinsoft Technology','Specialization':'AI, ML, Mobile & Web Development','HR Email':'hr@vrinsofts.com','General Email':'sales@vrinsofts.com','Phone':'+91 7227906117','Website':'vrinsofts.com','Address':'707, Elite Business Park, SG Highway, Ahmedabad 380060','Careers URL':'vrinsofts.com/careers'},
    {'No':13,'Company Name':'Growexx','Specialization':'AI Engineering, Oracle Solutions, Agile Dev','HR Email':'hr@growexx.com','General Email':'info@growexx.com','Phone':'07940394046','Website':'growexx.com','Address':'1105, Shivalik Abaise, Prahalad Nagar, Ahmedabad 380015','Careers URL':'growexx.com/careers'},
    {'No':14,'Company Name':'MindInventory','Specialization':'AI, ML, Mobile & Web App Development','HR Email':'hr@mindinventory.com','General Email':'info@mindinventory.com','Phone':'+91 9974390989','Website':'mindinventory.com','Address':'2 Science City Road, Gandhinagar, Gujarat 380060','Careers URL':'mindinventory.com/careers'},
    {'No':15,'Company Name':'eSparkBiz Technologies','Specialization':'AI, ML, Web & Mobile Development','HR Email':'hr@esparkinfo.com','General Email':'info@esparkinfo.com','Phone':'+91 9723352777','Website':'esparkinfo.com','Address':'Ahmedabad, Gujarat','Careers URL':'esparkinfo.com/careers'},
    {'No':16,'Company Name':'TOPS Infosolutions','Specialization':'AI, ML, Custom Software, Mobility','HR Email':'hr@topsinfosolutions.com','General Email':'careers@topsinfosolutions.com','Phone':'+91 7575000269','Website':'topsinfosolutions.com','Address':'905, Samedh Complex, Near Agrawal Plaza, C.G Road, Ellisbridge, Ahmedabad 380006','Careers URL':'topsinfosolutions.com/career'},
    {'No':17,'Company Name':'Bacancy Technology','Specialization':'AI, ML, Full-stack, Agile Development','HR Email':'hr@bacancytechnology.com','General Email':'info@bacancytechnology.com','Phone':'079-40037674','Website':'bacancytechnology.com','Address':'15-16, Times Corporate Park, Near Thaltej-Shilaj Rd, Thaltej, Ahmedabad 380059','Careers URL':'bacancytechnology.com/careers'},
    {'No':18,'Company Name':'ViitorCloud Technologies','Specialization':'AI, AR/VR, Digital Transformation','HR Email':'hr@viitorcloud.com','General Email':'support@viitorcloud.com','Phone':'+91 8488964723','Website':'viitorcloud.com','Address':'301-303, Avdhesh House, Opp. Gurudwara, Bodakdev, Ahmedabad 380054','Careers URL':'viitorcloud.com/careers'},
    {'No':19,'Company Name':'SPEC INDIA','Specialization':'AI, BI, Custom Enterprise Software','HR Email':'hr@spec-india.com','General Email':'usa@spec-india.com','Phone':'+91 79 4000 0013','Website':'spec-india.com','Address':'SPEC House, Parth Complex, Near Swastik Cross Roads, Navarangpura, Ahmedabad 380009','Careers URL':'spec-india.com/careers'},
    {'No':20,'Company Name':'Concetto Labs','Specialization':'AI, ML, Mobile & Web App Development','HR Email':'hr@concettolabs.com','General Email':'career@concettolabs.com','Phone':'+91 9904091237','Website':'concettolabs.com','Address':'Ahmedabad, Gujarat','Careers URL':'concettolabs.com/careers'},
    {'No':21,'Company Name':'Thinkwik','Specialization':'AI, ML, Digital Product Development','HR Email':'hr@thinkwik.com','General Email':'hello@thinkwik.com','Phone':'+91 7486900681','Website':'thinkwik.com','Address':'1110, Zion Z1, Sindhu Bhavan Marg, Bodakdev, Ahmedabad 380054','Careers URL':'thinkwik.com/careers'},
    {'No':22,'Company Name':'Space-O Technologies','Specialization':'AI-Powered Software Development','HR Email':'hr@spaceotechnologies.com','General Email':'info@spaceotechnologies.com','Phone':'+91 9316757277','Website':'spaceotechnologies.com','Address':'1005, 10th Floor, Abhishree Adroit, Mansi Circle, Ahmedabad 380015','Careers URL':'spaceotechnologies.com/careers'},
    {'No':23,'Company Name':'IIH Global','Specialization':'AI, Web & Mobile Development','HR Email':'hr@iihglobal.com','General Email':'info@iihglobal.com','Phone':'+91 79 4030 7259','Website':'iihglobal.com','Address':'C-503A, Ganesh Meridian, Nr. Gujarat High Court, S.G Highway, Sola, Ahmedabad','Careers URL':'iihglobal.com/careers'},
    {'No':24,'Company Name':'Perception System','Specialization':'AI, ML, Custom Software Development','HR Email':'hr@perceptionsystem.com','General Email':'info@perceptionsystem.com','Phone':'+91 9904111659','Website':'perceptionsystem.com','Address':'704, 7th Floor, Sakar-9, Nr. Reserve Bank, Ashram Road, Ahmedabad 380009','Careers URL':'perceptionsystem.com/careers'},
    {'No':25,'Company Name':'DRC Systems','Specialization':'AI, IoT, Custom Software, IT Consulting','HR Email':'hr@drcsystems.com','General Email':'info@drcsystems.com','Phone':'+91 79 2686 7777','Website':'drcsystems.com','Address':'24th Floor, GIFT Two Building, GIFT CITY, Gandhinagar 382050','Careers URL':'drcsystems.com/careers'},
    {'No':26,'Company Name':'Citrusbug Technolabs','Specialization':'AI, ML, Web & Mobile Development','HR Email':'hr@citrusbug.com','General Email':'info@citrusbug.com','Phone':'+91 8128442240','Website':'citrusbug.com','Address':'A 411, Shivalik Corporate Park, Satellite, Ahmedabad 380015','Careers URL':'citrusbug.com/careers'},
    {'No':27,'Company Name':'Crest Coder Pvt Ltd','Specialization':'AI/ML, Blockchain, Digital Transformation','HR Email':'hr@crestcoder.com','General Email':'info@crestcoder.com','Phone':'+91 8044566771','Website':'crestcoder.com','Address':'802 B, Synergy Tower, Corporate Road, Ahmedabad 380015','Careers URL':'crestcoder.com/careers'},
    {'No':28,'Company Name':'InheritX Solutions','Specialization':'AI, ML, Web & Mobile Apps','HR Email':'hr@inheritx.com','General Email':'contact@inheritx.com','Phone':'+91 9492588586','Website':'inheritx.com','Address':'8th Floor, Panch Dhara Complex, Sarkhej-Gandhinagar Hwy, Bodakdev, Ahmedabad 380054','Careers URL':'inheritx.com/careers'},
    {'No':29,'Company Name':'SoluteLabs','Specialization':'AI, ML, Product Engineering','HR Email':'hr@solutelabs.com','General Email':'contactus@solutelabs.com','Phone':'+91 79 4891 7000','Website':'solutelabs.com','Address':'A1-104, Palladium, Corporate Road, Prahladnagar, Ahmedabad 380015','Careers URL':'solutelabs.com/careers'},
    {'No':30,'Company Name':'Tridhya Tech Limited','Specialization':'AI, eCommerce, Web & Mobile Development','HR Email':'hr@tridhyatech.com','General Email':'info@tridhyatech.com','Phone':'+91 79 4891 2700','Website':'tridhyatech.com','Address':'4th Floor, One World West, Ambali T Junction, Bopal, Ahmedabad 380058','Careers URL':'tridhyatech.com/careers'},
    {'No':31,'Company Name':'ScaleTech Solutions','Specialization':'AI/ML, Data Engineering, SportsTech','HR Email':'hr@scaletech.xyz','General Email':'info@scaletech.xyz','Phone':'08849159450','Website':'scaletech.xyz','Address':'A-402, Shapath Hexa Near Sola Bridge, Sarkhej-Gandhinagar Hwy, Sola, Ahmedabad 380060','Careers URL':'scaletech.xyz/career'},
    {'No':32,'Company Name':'Intuz','Specialization':'AI, Custom Software, Mobile Apps','HR Email':'hr@intuz.com','General Email':'careers@intuz.info','Phone':'+91 9904929149','Website':'intuz.com','Address':'910, Pinnacle, Corporate Road, Prahlad Nagar, Ahmedabad 380015','Careers URL':'intuz.com/career'},
    {'No':33,'Company Name':'WPWeb Infotech','Specialization':'AI, WordPress, eCommerce Development','HR Email':'hr@wpwebinfotech.com','General Email':'jigar@wpwebinfotech.com','Phone':'+91 8488812163','Website':'wpwebinfotech.com','Address':'Ahmedabad, Gujarat','Careers URL':'wpwebinfotech.com/careers'},
    {'No':34,'Company Name':'Inferenz','Specialization':'Data and AI Solutions, ML Engineering','HR Email':'careers@inferenz.ai','General Email':'inferenz.ai@gmail.com','Phone':'N/A','Website':'inferenz.ai','Address':'Ahmedabad, Gujarat','Careers URL':'inferenz.ai/careers'},
    {'No':35,'Company Name':'TRooTech Business Solutions','Specialization':'AI/ML, Digital Transformation, Software Dev','HR Email':'hr@trootech.com','General Email':'info@trootech.com','Phone':'+91 9904929149','Website':'trootech.com','Address':'Ahmedabad, Gujarat','Careers URL':'trootech.com/careers'},
    {'No':36,'Company Name':'DevsTree IT Services','Specialization':'AI/ML, Data Engineering, IoT, Web & Mobile','HR Email':'hr@devstree.com','General Email':'info@devstree.com','Phone':'+91 9558833117','Website':'devstree.com','Address':'B-433-442, Money Plant High Street, SG Highway, Ahmedabad 382470','Careers URL':'devstree.com/careers'},
    {'No':37,'Company Name':'DataDwip','Specialization':'AI/ML Data Intelligence, Web Scraping, Annotation','HR Email':'hr@datadwip.com','General Email':'info@datadwip.com','Phone':'N/A','Website':'datadwip.com','Address':'RE11, Near Vikramnagar, Iscon Ambli, Ahmedabad 380058','Careers URL':'datadwip.com/careers'},
    {'No':38,'Company Name':'fxis.ai (F(x) Data Labs)','Specialization':'AI, Data Science, Neural Networks, ML','HR Email':'hr@fxis.ai','General Email':'info@fxis.ai','Phone':'N/A','Website':'fxis.ai','Address':'Ahmedabad, Gujarat','Careers URL':'fxis.ai/careers'},
    {'No':39,'Company Name':'Rushkar Technology','Specialization':'AI, Software Development, Web & Mobile','HR Email':'hr@rushkar.com','General Email':'info@rushkar.com','Phone':'+91 8980544320','Website':'rushkar.com','Address':'411, Sarthik Square, SG Highway, Bodakdev, Ahmedabad 380054','Careers URL':'rushkar.com/careers'},
    {'No':40,'Company Name':'PranshTech Solutions','Specialization':'AI/ML, Web & Mobile Apps, QA','HR Email':'hr@pranshtech.com','General Email':'info@pranshtech.com','Phone':'N/A','Website':'pranshtech.com','Address':'Ahmedabad, Gujarat','Careers URL':'pranshtech.com/careers'},
    {'No':41,'Company Name':'Incipient Infotech','Specialization':'AI, ML, Software Consulting','HR Email':'hr@incipientinfotech.com','General Email':'info@incipientinfotech.com','Phone':'+91 9586083980','Website':'incipientinfotech.com.au','Address':'612-614, Lilamani Corporate Heights, Ahmedabad','Careers URL':'incipientinfotech.com.au/careers'},
    {'No':42,'Company Name':'SolGuruz','Specialization':'AI, Mobile & Web App Development','HR Email':'hr@solguruz.com','General Email':'info@solguruz.com','Phone':'+91 9898956660','Website':'solguruz.com','Address':'Ahmedabad, Gujarat','Careers URL':'solguruz.com/careers'},
    {'No':43,'Company Name':'iQlance Solutions','Specialization':'AI, Mobile & Web Development','HR Email':'hr@iqlance.com','General Email':'info@iqlance.com','Phone':'+91 9173222000','Website':'iqlance.com','Address':'Ahmedabad, Gujarat','Careers URL':'iqlance.com/careers'},
    {'No':44,'Company Name':'Glib.ai','Specialization':'AI Document Processing, ML, Lending Automation','HR Email':'hr@glib.ai','General Email':'info@glib.ai','Phone':'+1 716-218-3242','Website':'glib.ai','Address':'Ahmedabad, Gujarat 380059','Careers URL':'glib.ai/careers'},
    {'No':45,'Company Name':'Indian TTS','Specialization':'AI, NLP, Text-to-Speech, Speech-to-Text','HR Email':'hr@indiantts.com','General Email':'info@indiantts.com','Phone':'N/A','Website':'indiantts.com','Address':'Ahmedabad, Gujarat','Careers URL':'indiantts.com/careers'},
    {'No':46,'Company Name':'Metis Intellisystems','Specialization':'AI-powered Decision Support Software','HR Email':'hr@metisintel.in','General Email':'info@metisintel.in','Phone':'N/A','Website':'metisintel.in','Address':'Ahmedabad, Gujarat','Careers URL':'metisintel.in/careers'},
    {'No':47,'Company Name':'Oizom','Specialization':'AI, IoT, Air Quality Monitoring, Environment Tech','HR Email':'hr@oizom.com','General Email':'info@oizom.com','Phone':'+91 9974003765','Website':'oizom.com','Address':'Ahmedabad, Gujarat','Careers URL':'oizom.com/careers'},
    {'No':48,'Company Name':'Saarthi Pedagogy','Specialization':'AI, EdTech, Pedagogy Solutions','HR Email':'hr@saarthipedagogy.com','General Email':'info@saarthipedagogy.com','Phone':'N/A','Website':'saarthipedagogy.com','Address':'Novatel, Ramdev Nagar, Ahmedabad','Careers URL':'saarthipedagogy.com/careers'},
    {'No':49,'Company Name':'CodesClue Technologies','Specialization':'AI/ML, Blockchain, Digital Transformation','HR Email':'hr@codesclue.com','General Email':'info@codesclue.com','Phone':'N/A','Website':'codesclue.com','Address':'Ahmedabad, Gujarat','Careers URL':'codesclue.com/careers'},
    {'No':50,'Company Name':'Growth Loops Technology','Specialization':'AI, Mobile App, UI/UX Design','HR Email':'hr@growthloops.com','General Email':'info@growthloops.com','Phone':'N/A','Website':'growthloops.com','Address':'Ahmedabad, Gujarat','Careers URL':'growthloops.com/careers'},
    {'No':51,'Company Name':'TechnoYuga Soft','Specialization':'AI, Mobile & Web App Development, UI/UX','HR Email':'hr@technoyuga.com','General Email':'info@technoyuga.com','Phone':'+91 9974111099','Website':'technoyuga.com','Address':'Ahmedabad, Gujarat','Careers URL':'technoyuga.com/careers'},
    {'No':52,'Company Name':'TechGropse','Specialization':'AI, ML, Mobile App Development','HR Email':'hr@techgropse.com','General Email':'info@techgropse.com','Phone':'+91 9999010991','Website':'techgropse.com','Address':'Ahmedabad, Gujarat','Careers URL':'techgropse.com/careers'},
    {'No':53,'Company Name':'Mobio Solutions','Specialization':'AI, Business Technology Solutions','HR Email':'hr@mobiosolutions.com','General Email':'info@mobiosolutions.com','Phone':'+91 9904929149','Website':'mobiosolutions.com','Address':'B-706, Ganesh Plaza, Nr Navrangpura Bus Stop, Navrangpura, Ahmedabad 380009','Careers URL':'mobiosolutions.com/careers'},
    {'No':54,'Company Name':'Inexture Solutions','Specialization':'AI, Python, Java, Enterprise Software','HR Email':'hr@inexture.com','General Email':'info@inexture.com','Phone':'+91 6353697824','Website':'inexture.com','Address':'Office No. 405, One World West, Near Ambli T-Junction, Bopal, Ahmedabad 380058','Careers URL':'inexture.com/careers'},
    {'No':55,'Company Name':'Nexgits','Specialization':'AI/ML, AR/VR, Custom Software','HR Email':'hr@nexgits.com','General Email':'info@nexgits.com','Phone':'N/A','Website':'nexgits.com','Address':'Ahmedabad, Gujarat','Careers URL':'nexgits.com/careers'},
    {'No':56,'Company Name':'DGTL Innovations','Specialization':'AI, Data Science, Digital Transformation','HR Email':'hr@dgtlinnovations.in','General Email':'info@dgtlinnovations.in','Phone':'N/A','Website':'dgtlinnovations.in','Address':'Ahmedabad, Gujarat','Careers URL':'dgtlinnovations.in/careers'},
    {'No':57,'Company Name':'NexusLink Services India','Specialization':'AI, IT Outsourcing, Offshore Development','HR Email':'hr@nexuslinkindia.com','General Email':'info@nexuslinkindia.com','Phone':'N/A','Website':'nexuslinkindia.com','Address':'Ahmedabad, Gujarat','Careers URL':'nexuslinkindia.com/careers'},
    {'No':58,'Company Name':'Infibeam Avenues','Specialization':'AI, FinTech, Payments, AI Hub GIFT City','HR Email':'hr@ia.ooo','General Email':'info@ia.ooo','Phone':'+91 796 777 2201','Website':'ia.ooo','Address':'28th Floor, GIFT Two Building, GIFT CITY, Gandhinagar 382355','Careers URL':'ia.ooo/careers'},
    {'No':59,'Company Name':'Sigma Infosolutions','Specialization':'AI, eCommerce, FinTech, Product Dev','HR Email':'hr@sigmainfo.net','General Email':'info@sigmainfo.net','Phone':'+91 79 4000 0520','Website':'sigmainfo.net','Address':'Ahmedabad, Gujarat','Careers URL':'sigmainfo.net/careers'},
    {'No':60,'Company Name':'Brainvire Infotech','Specialization':'AI, CRM, ERP, Web & Mobile Development','HR Email':'hr@brainvire.com','General Email':'info@brainvire.com','Phone':'+91 79 6194 0000','Website':'brainvire.com','Address':'Sheth Corporate Tower, 9th Floor, Ellisbridge, Ahmedabad 380009','Careers URL':'brainvire.com/careers'},
    {'No':61,'Company Name':'Peerbits','Specialization':'AI, Mobile & Web App Development','HR Email':'hr@peerbits.com','General Email':'nahidvhora@yahoo.com','Phone':'+91 8044464841','Website':'peerbits.com','Address':'2nd Floor, Meem Procon Pvt Ltd, Nr. Indraprastha Business Park, Makarba, Ahmedabad 380051','Careers URL':'peerbits.com/careers'},
    {'No':62,'Company Name':'Sparx IT Solutions','Specialization':'AI, ML, Digital Transformation, Cybersecurity','HR Email':'hr@sparxitsolutions.com','General Email':'info@sparxitsolutions.com','Phone':'+91 9979800440','Website':'sparxitsolutions.com','Address':'Ahmedabad, Gujarat','Careers URL':'sparxitsolutions.com/careers'},
    {'No':63,'Company Name':'Nimap Infotech','Specialization':'AI, Automation, Web & Mobile Development','HR Email':'hr@nimapinfotech.com','General Email':'info@nimapinfotech.com','Phone':'+91 9820253369','Website':'nimapinfotech.com','Address':'Ahmedabad, Gujarat','Careers URL':'nimapinfotech.com/careers'},
    {'No':64,'Company Name':'Dwij AI Labs','Specialization':'AI Engineering Teams, AI-native Development','HR Email':'hr@dwijailabs.com','General Email':'info@dwijailabs.com','Phone':'N/A','Website':'dwijailabs.com','Address':'Ahmedabad, Gujarat','Careers URL':'dwijailabs.com/careers'},
    {'No':65,'Company Name':'Junkies Coder','Specialization':'AI, App & Software Development','HR Email':'hr@junkiescoder.com','General Email':'info@junkiescoder.com','Phone':'N/A','Website':'junkiescoder.com','Address':'Ahmedabad, Gujarat','Careers URL':'junkiescoder.com/careers'},
    {'No':66,'Company Name':'WOGOM','Specialization':'AI, B2B Marketplace, Digital Commerce','HR Email':'hr@wogom.com','General Email':'info@wogom.com','Phone':'N/A','Website':'wogom.com','Address':'Ahmedabad, Gujarat','Careers URL':'wogom.com/careers'},
    {'No':67,'Company Name':'Ishitva Robotics','Specialization':'AI, Robotics, Automation Solutions','HR Email':'hr@ishitva.com','General Email':'info@ishitva.com','Phone':'N/A','Website':'ishitva.com','Address':'Ahmedabad, Gujarat','Careers URL':'ishitva.com/careers'},
    {'No':68,'Company Name':'Prompt Softech','Specialization':'AI, Product Engineering, Software Dev','HR Email':'hr@promptsoftech.com','General Email':'info@promptsoftech.com','Phone':'+91 9725627575','Website':'promptsoftech.com','Address':'Ahmedabad, Gujarat','Careers URL':'promptsoftech.com/careers'},
    {'No':69,'Company Name':'Emgage','Specialization':'AI, HR Tech, Employee Engagement','HR Email':'hr@emgage.com','General Email':'info@emgage.com','Phone':'N/A','Website':'emgage.com','Address':'Ahmedabad, Gujarat','Careers URL':'emgage.com/careers'},
    {'No':70,'Company Name':'Softvan','Specialization':'AI, ERP, Web & Software Development','HR Email':'hr@softvan.in','General Email':'info@softvan.in','Phone':'+91 9909942743','Website':'softvan.in','Address':'Ahmedabad, Gujarat','Careers URL':'softvan.in/careers'},
    {'No':71,'Company Name':'MagnusMinds IT Solution','Specialization':'AI, ML, Web & Mobile Development','HR Email':'hr@magnusminds.net','General Email':'info@magnusminds.net','Phone':'+91 9228900445','Website':'magnusminds.net','Address':'Ahmedabad, Gujarat','Careers URL':'magnusminds.net/careers'},
    {'No':72,'Company Name':'Semaphore Software','Specialization':'AI, ML, IoT, Custom Software','HR Email':'hr@semaphore-software.com','General Email':'info@semaphore-software.com','Phone':'+91 9974334455','Website':'semaphore-software.com','Address':'Ahmedabad, Gujarat','Careers URL':'semaphore-software.com/careers'},
    {'No':73,'Company Name':'Ksolves India','Specialization':'AI, Odoo ERP, Python, Data Science','HR Email':'hr@ksolves.com','General Email':'info@ksolves.com','Phone':'+91 9205086544','Website':'ksolves.com','Address':'Ahmedabad, Gujarat','Careers URL':'ksolves.com/careers'},
    {'No':74,'Company Name':'Nimblechapps','Specialization':'AI, Mobile App, React Native','HR Email':'hr@nimblechapps.com','General Email':'info@nimblechapps.com','Phone':'+91 9998880705','Website':'nimblechapps.com','Address':'Ahmedabad, Gujarat','Careers URL':'nimblechapps.com/careers'},
    {'No':75,'Company Name':'Uplers','Specialization':'AI, Digital Marketing, Talent Solutions','HR Email':'hr@uplers.com','General Email':'info@uplers.com','Phone':'+91 8000 231 231','Website':'uplers.com','Address':'Ahmedabad, Gujarat','Careers URL':'uplers.com/careers'},
    {'No':76,'Company Name':'Techila Global Services','Specialization':'AI, Big Data, Software Staffing','HR Email':'hr@techilaglobal.com','General Email':'info@techilaglobal.com','Phone':'+91 9687798898','Website':'techilaglobal.com','Address':'Ahmedabad, Gujarat','Careers URL':'techilaglobal.com/careers'},
    {'No':77,'Company Name':'Mobisoft Infotech','Specialization':'AI, Mobile App, IoT, Cloud Development','HR Email':'hr@mobisoftinfotech.com','General Email':'info@mobisoftinfotech.com','Phone':'+1 832-291-3103','Website':'mobisoftinfotech.com','Address':'Ahmedabad, Gujarat','Careers URL':'mobisoftinfotech.com/careers'},
    {'No':78,'Company Name':'Openwave Computing','Specialization':'AI, Business Intelligence, Software Dev','HR Email':'hr@openwavecomputing.com','General Email':'info@openwavecomputing.com','Phone':'+91 79 4000 1000','Website':'openwavecomputing.com','Address':'Ahmedabad, Gujarat','Careers URL':'openwavecomputing.com/careers'},
    {'No':79,'Company Name':'Codeyeti Software Solutions','Specialization':'AI, ML, Web & Mobile Dev','HR Email':'hr@codeyeti.com','General Email':'info@codeyeti.com','Phone':'N/A','Website':'codeyeti.com','Address':'Ahmedabad, Gujarat','Careers URL':'codeyeti.com/careers'},
    {'No':80,'Company Name':'Creolestudios','Specialization':'AI, Mobile & Web App Development','HR Email':'hr@creolestudios.com','General Email':'info@creolestudios.com','Phone':'+91 9904461614','Website':'creolestudios.com','Address':'Ahmedabad, Gujarat','Careers URL':'creolestudios.com/careers'},
    {'No':81,'Company Name':'360 Degree Cloud','Specialization':'AI, Salesforce, Cloud Solutions','HR Email':'hr@360degreecloud.com','General Email':'info@360degreecloud.com','Phone':'+1 309-316-7929','Website':'360degreecloud.com','Address':'Ahmedabad, Gujarat','Careers URL':'360degreecloud.com/careers'},
    {'No':82,'Company Name':'Xorlogics','Specialization':'AI, ML, Blockchain, IoT','HR Email':'hr@xorlogics.com','General Email':'info@xorlogics.com','Phone':'N/A','Website':'xorlogics.com','Address':'Ahmedabad, Gujarat','Careers URL':'xorlogics.com/careers'},
    {'No':83,'Company Name':'Saffron Tech','Specialization':'AI, Chatbot, Software Development','HR Email':'hr@saffrontech.net','General Email':'info@saffrontech.net','Phone':'+91 9899650100','Website':'saffrontech.net','Address':'Ahmedabad, Gujarat','Careers URL':'saffrontech.net/careers'},
    {'No':84,'Company Name':'Aelum Consulting','Specialization':'AI, Salesforce, Data Analytics','HR Email':'hr@aelumconsulting.com','General Email':'info@aelumconsulting.com','Phone':'+91 9979882298','Website':'aelumconsulting.com','Address':'Ahmedabad, Gujarat','Careers URL':'aelumconsulting.com/careers'},
    {'No':85,'Company Name':'Optimus Information','Specialization':'AI, Quality Engineering, Digital Testing','HR Email':'hr@optimusinfo.com','General Email':'info@optimusinfo.com','Phone':'+1 604-629-9494','Website':'optimusinfo.com','Address':'Ahmedabad, Gujarat','Careers URL':'optimusinfo.com/careers'},
    {'No':86,'Company Name':'Elogictech Solutions','Specialization':'AI, IoT, Embedded Systems','HR Email':'hr@elogictech.com','General Email':'info@elogictech.com','Phone':'+91 9904571166','Website':'elogictech.com','Address':'Ahmedabad, Gujarat','Careers URL':'elogictech.com/careers'},
    {'No':87,'Company Name':'Sapphire Software Solutions','Specialization':'AI, ERP, SAP, Custom Software','HR Email':'hr@sapphiresolutions.net','General Email':'info@sapphiresolutions.net','Phone':'+91 79 2694 0408','Website':'sapphiresolutions.net','Address':'Ahmedabad, Gujarat','Careers URL':'sapphiresolutions.net/careers'},
    {'No':88,'Company Name':'Concord Infotech','Specialization':'AI, Web, Mobile, Offshore Development','HR Email':'hr@concordinfotech.com','General Email':'info@concordinfotech.com','Phone':'+91 9924055215','Website':'concordinfotech.com','Address':'Ahmedabad, Gujarat','Careers URL':'concordinfotech.com/careers'},
    {'No':89,'Company Name':'KloudMate','Specialization':'AI, Cloud Observability, DevOps','HR Email':'hr@kloudmate.com','General Email':'info@kloudmate.com','Phone':'N/A','Website':'kloudmate.com','Address':'Ahmedabad, Gujarat','Careers URL':'kloudmate.com/careers'},
    {'No':90,'Company Name':'Devtechnosys','Specialization':'AI, ML, Mobile & Web Development','HR Email':'hr@devtechnosys.com','General Email':'info@devtechnosys.com','Phone':'+91 9815031753','Website':'devtechnosys.com','Address':'Ahmedabad, Gujarat','Careers URL':'devtechnosys.com/careers'},
    {'No':91,'Company Name':'ValueCoders','Specialization':'AI, ML, Offshore Software Development','HR Email':'hr@valuecoders.com','General Email':'info@valuecoders.com','Phone':'+91 8750042229','Website':'valuecoders.com','Address':'Ahmedabad, Gujarat','Careers URL':'valuecoders.com/careers'},
    {'No':92,'Company Name':'Tuvoc Technologies','Specialization':'AI, ML, Cloud, DevOps','HR Email':'hr@tuvoc.com','General Email':'info@tuvoc.com','Phone':'N/A','Website':'tuvoc.com','Address':'Ahmedabad, Gujarat','Careers URL':'tuvoc.com/careers'},
    {'No':93,'Company Name':'ThinkResource Infosolutions','Specialization':'AI, Data Science, IT Staffing','HR Email':'hr@thinkresource.in','General Email':'info@thinkresource.in','Phone':'+91 9898540086','Website':'thinkresource.in','Address':'Ahmedabad, Gujarat','Careers URL':'thinkresource.in/careers'},
    {'No':94,'Company Name':'WebLineIndia','Specialization':'AI, Web Development, Digital Marketing','HR Email':'hr@weblineindia.com','General Email':'info@weblineindia.com','Phone':'+91 9727600446','Website':'weblineindia.com','Address':'Ahmedabad, Gujarat','Careers URL':'weblineindia.com/careers'},
    {'No':95,'Company Name':'Mobiloitte','Specialization':'AI, Chatbot, AR/VR, Mobile Development','HR Email':'hr@mobiloitte.com','General Email':'info@mobiloitte.com','Phone':'+91 7899001199','Website':'mobiloitte.com','Address':'Ahmedabad, Gujarat','Careers URL':'mobiloitte.com/careers'},
    {'No':96,'Company Name':'Techracers','Specialization':'AI, Chatbot, Automation, RPA','HR Email':'hr@techracers.com','General Email':'info@techracers.com','Phone':'N/A','Website':'techracers.com','Address':'Ahmedabad, Gujarat','Careers URL':'techracers.com/careers'},
    {'No':97,'Company Name':'Emizion Solutions','Specialization':'AI, ML, Digital Transformation','HR Email':'hr@emizion.com','General Email':'info@emizion.com','Phone':'N/A','Website':'emizion.com','Address':'Ahmedabad, Gujarat','Careers URL':'emizion.com/careers'},
    {'No':98,'Company Name':'Parth Solutions','Specialization':'AI, ERP, HR Software, Payroll','HR Email':'hr@parthsolutions.com','General Email':'info@parthsolutions.com','Phone':'+91 79 2646 1730','Website':'parthsolutions.com','Address':'Ahmedabad, Gujarat','Careers URL':'parthsolutions.com/careers'},
    {'No':99,'Company Name':'AllianceTek','Specialization':'AI, Custom Software, Web & Mobile Development','HR Email':'hr@alliancetek.com','General Email':'info@alliancetek.com','Phone':'484-892-5713','Website':'alliancetek.com','Address':'Ahmedabad, Gujarat','Careers URL':'alliancetek.com/careers'},
    {'No':100,'Company Name':'Prompt Infosystems','Specialization':'AI, ERP, CRM, Business Software','HR Email':'hr@promptinfosystems.com','General Email':'info@promptinfosystems.com','Phone':'+91 79 2646 0505','Website':'promptinfosystems.com','Address':'Ahmedabad, Gujarat','Careers URL':'promptinfosystems.com/careers'},
]

df = pd.DataFrame(companies)

output_path = r'c:\Users\Capermint\Project\linkdin\Ahmedabad_AIML_Companies_HR_Contacts.xlsx'

with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
    df.to_excel(writer, index=False, sheet_name='AIML Companies')
    ws = writer.sheets['AIML Companies']

    # Header styling
    header_fill = PatternFill(start_color='1F4E79', end_color='1F4E79', fill_type='solid')
    header_font = Font(color='FFFFFF', bold=True, size=11)
    header_align = Alignment(horizontal='center', vertical='center', wrap_text=True)

    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = header_align

    # Row alternating colors
    light_blue = PatternFill(start_color='DDEEFF', end_color='DDEEFF', fill_type='solid')
    white = PatternFill(start_color='FFFFFF', end_color='FFFFFF', fill_type='solid')

    for row_idx, row in enumerate(ws.iter_rows(min_row=2, max_row=ws.max_row), start=1):
        fill = light_blue if row_idx % 2 == 0 else white
        for cell in row:
            cell.fill = fill
            cell.alignment = Alignment(vertical='center', wrap_text=True)

    # Column widths
    col_widths = {'No': 5, 'Company Name': 28, 'Specialization': 38, 'HR Email': 32,
                  'General Email': 32, 'Phone': 20, 'Website': 28, 'Address': 50, 'Careers URL': 35}
    for col_num, col in enumerate(ws.iter_cols(min_row=1, max_row=1), start=1):
        col_name = col[0].value
        width = col_widths.get(col_name, 20)
        ws.column_dimensions[get_column_letter(col_num)].width = width

    # Row height
    ws.row_dimensions[1].height = 30
    for row in range(2, ws.max_row + 1):
        ws.row_dimensions[row].height = 20

    # Freeze top row
    ws.freeze_panes = 'A2'

    # Auto filter
    ws.auto_filter.ref = ws.dimensions

print(f'Excel file created: {output_path}')
print(f'Total companies: {len(df)}')
print('Columns:', list(df.columns))
