# -*- coding: utf-8 -*-
"""
Decode Forest Pharmacy — static knowledge base.
All data is hand-curated; real deployments should connect to a live
medicine/drug-interaction database (e.g. OpenFDA, RxNorm, CIMS India).
"""

from __future__ import annotations

# ── Medicines catalogue ───────────────────────────────────────────────────────
MEDICINES: list[dict] = [
    {"name": "Paracetamol (500 mg)", "generic": "Paracetamol", "brand": "Calpol / Dolo 650",
     "category": "Analgesic / Antipyretic", "use": "Fever, mild to moderate pain relief.",
     "dose": "500–1000 mg every 4–6 hours (max 4 g/day)", "side_effects": "Rare at normal doses; overdose → liver damage.",
     "avoid": "Alcohol, liver disease, high doses", "price_inr": "15–30"},
    {"name": "Ibuprofen (400 mg)", "generic": "Ibuprofen", "brand": "Brufen / Combiflam",
     "category": "NSAID", "use": "Pain, inflammation, fever.",
     "dose": "400 mg every 6–8 hours after food", "side_effects": "Gastric irritation, kidney strain with prolonged use.",
     "avoid": "Peptic ulcer, renal impairment, last trimester pregnancy", "price_inr": "20–50"},
    {"name": "Amoxicillin (500 mg)", "generic": "Amoxicillin", "brand": "Mox / Amoxil",
     "category": "Antibiotic (Penicillin)", "use": "Bacterial infections — respiratory, UTI, ear infections.",
     "dose": "500 mg every 8 hours for 5–7 days (as prescribed)", "side_effects": "Nausea, diarrhoea, allergic rash.",
     "avoid": "Penicillin allergy; always complete the full course", "price_inr": "80–150"},
    {"name": "Metformin (500 mg)", "generic": "Metformin HCl", "brand": "Glycomet / Glucophage",
     "category": "Antidiabetic (Biguanide)", "use": "Type 2 diabetes management.",
     "dose": "500 mg with meals; titrate to 1–2 g/day under supervision", "side_effects": "Nausea, diarrhoea, lactic acidosis (rare).",
     "avoid": "Renal impairment (eGFR<30), iodinated contrast dye within 48 h", "price_inr": "25–60"},
    {"name": "Atorvastatin (10 mg)", "generic": "Atorvastatin", "brand": "Lipitor / Atorva",
     "category": "Statin", "use": "Lowers LDL cholesterol; reduces cardiovascular risk.",
     "dose": "10–80 mg once daily at bedtime", "side_effects": "Muscle pain (myopathy), elevated liver enzymes.",
     "avoid": "Liver disease, pregnancy, grapefruit juice", "price_inr": "30–90"},
    {"name": "Omeprazole (20 mg)", "generic": "Omeprazole", "brand": "Omez / Prilosec",
     "category": "Proton Pump Inhibitor (PPI)", "use": "Gastric ulcers, GERD, heartburn.",
     "dose": "20–40 mg once daily 30 min before food", "side_effects": "Headache, diarrhoea, vitamin B12 deficiency (long-term).",
     "avoid": "Long-term use without indication; check clopidogrel interaction", "price_inr": "20–55"},
    {"name": "Cetirizine (10 mg)", "generic": "Cetirizine HCl", "brand": "Zyrtec / Cetzine",
     "category": "Antihistamine (2nd gen)", "use": "Allergic rhinitis, urticaria, hay fever.",
     "dose": "10 mg once daily (evening to reduce drowsiness)", "side_effects": "Mild drowsiness, dry mouth.",
     "avoid": "Heavy machinery operation if drowsy; renal impairment → reduce dose", "price_inr": "15–40"},
    {"name": "Azithromycin (500 mg)", "generic": "Azithromycin", "brand": "Zithromax / Azee",
     "category": "Antibiotic (Macrolide)", "use": "Respiratory tract infections, sinusitis, STIs.",
     "dose": "500 mg day 1, then 250 mg days 2–5", "side_effects": "Nausea, abdominal pain, QT prolongation (cardiac).",
     "avoid": "Antacids within 2 h; cardiac arrhythmia history", "price_inr": "100–200"},
    {"name": "Losartan (50 mg)", "generic": "Losartan Potassium", "brand": "Cozaar / Losar",
     "category": "ARB (Antihypertensive)", "use": "Hypertension, diabetic nephropathy.",
     "dose": "50 mg once daily; may increase to 100 mg", "side_effects": "Dizziness, hyperkalemia, impaired renal function.",
     "avoid": "Pregnancy, hyperkalemia, ACE inhibitor combination (usually)", "price_inr": "40–100"},
    {"name": "Levothyroxine (50 mcg)", "generic": "Levothyroxine Sodium", "brand": "Thyronorm / Eltroxin",
     "category": "Thyroid Hormone", "use": "Hypothyroidism replacement therapy.",
     "dose": "50–200 mcg once daily on empty stomach 30 min before food", "side_effects": "Palpitations, insomnia, weight loss (if overdosed).",
     "avoid": "Calcium/iron supplements within 4 h; soya products", "price_inr": "20–65"},
    {"name": "Aspirin (75 mg)", "generic": "Acetylsalicylic Acid", "brand": "Ecosprin / Aspirin",
     "category": "Antiplatelet / NSAID", "use": "Antiplatelet for cardiovascular protection; fever/pain at higher doses.",
     "dose": "75–100 mg once daily (cardioprotection); 300–600 mg for pain", "side_effects": "GI bleeding, tinnitus at high doses.",
     "avoid": "Children under 16 (Reye's syndrome), peptic ulcer, anticoagulants", "price_inr": "10–30"},
    {"name": "Vitamin D3 (60,000 IU)", "generic": "Cholecalciferol", "brand": "D3 Must / Calcirol",
     "category": "Vitamin Supplement", "use": "Vitamin D deficiency, bone health, immune support.",
     "dose": "60,000 IU once weekly for 8 weeks (loading); then monthly maintenance", "side_effects": "Hypercalcemia (if excessive), nausea.",
     "avoid": "Hypercalcemia; do not self-medicate high doses without blood test", "price_inr": "30–80"},
]

# ── Drug interaction pairs ────────────────────────────────────────────────────
INTERACTIONS: list[dict] = [
    {"drug_a": "Warfarin", "drug_b": "Aspirin",
     "severity": "HIGH", "effect": "Increased bleeding risk — both inhibit clotting via different pathways.",
     "advice": "Avoid combination unless under close specialist monitoring."},
    {"drug_a": "Metformin", "drug_b": "Iodinated Contrast Dye",
     "severity": "HIGH", "effect": "Risk of lactic acidosis — hold Metformin 48 h before/after contrast procedure.",
     "advice": "Withhold Metformin 48 h around contrast imaging; restart after renal function confirmed normal."},
    {"drug_a": "Omeprazole", "drug_b": "Clopidogrel",
     "severity": "MODERATE", "effect": "Omeprazole inhibits CYP2C19 reducing clopidogrel antiplatelet effect.",
     "advice": "Use Pantoprazole instead of Omeprazole when on Clopidogrel."},
    {"drug_a": "Losartan", "drug_b": "Potassium Supplements",
     "severity": "MODERATE", "effect": "Both raise serum potassium → hyperkalemia risk.",
     "advice": "Monitor potassium levels regularly; avoid routine potassium supplementation."},
    {"drug_a": "Atorvastatin", "drug_b": "Clarithromycin",
     "severity": "HIGH", "effect": "Clarithromycin inhibits CYP3A4, raising statin levels → myopathy / rhabdomyolysis risk.",
     "advice": "Temporarily stop Atorvastatin during short antibiotic courses. Switch to Azithromycin if feasible."},
    {"drug_a": "Levothyroxine", "drug_b": "Calcium Carbonate",
     "severity": "MODERATE", "effect": "Calcium binds Levothyroxine in gut, reducing absorption.",
     "advice": "Take Levothyroxine at least 4 hours apart from calcium supplements."},
    {"drug_a": "Ibuprofen", "drug_b": "Losartan",
     "severity": "MODERATE", "effect": "NSAIDs reduce antihypertensive efficacy and increase renal impairment risk.",
     "advice": "Prefer Paracetamol for pain relief when on antihypertensives."},
    {"drug_a": "Azithromycin", "drug_b": "Amiodarone",
     "severity": "HIGH", "effect": "Both prolong QT interval — risk of fatal arrhythmia.",
     "advice": "Avoid combination. Consult cardiologist for alternative antibiotic."},
    {"drug_a": "Metformin", "drug_b": "Alcohol",
     "severity": "MODERATE", "effect": "Alcohol potentiates lactic acidosis risk with Metformin.",
     "advice": "Limit or avoid alcohol during Metformin therapy."},
    {"drug_a": "Aspirin", "drug_b": "Ibuprofen",
     "severity": "MODERATE", "effect": "Ibuprofen may block Aspirin's antiplatelet effect if taken before it.",
     "advice": "Take Aspirin 30 min before Ibuprofen, or use Paracetamol for pain relief."},
]

# ── Health assistant knowledge ────────────────────────────────────────────────
HEALTH_KNOWLEDGE: list[tuple[str, str]] = [
    ("Prescription Reading — What to look for",
     "A valid prescription includes: patient name, date, drug name (generic preferred), dose, frequency, duration, prescriber name & registration number. Reject any prescription that lacks these."),
    ("Drug Interactions — Overview",
     "Drug interactions occur when two or more drugs affect each other's activity. Pharmacokinetic interactions (absorption, metabolism, excretion) and pharmacodynamic interactions (additive, synergistic, or antagonistic effects) are the two main types. Always disclose all medicines including OTC and supplements to your doctor and pharmacist."),
    ("Generic vs Brand Medicines",
     "Generic medicines contain the same active ingredient, strength, dosage form and route of administration as the brand but cost 30–80% less. They are bioequivalent and regulated by the CDSCO in India. Ask your pharmacist for safe generic substitutes."),
    ("Antibiotic Resistance",
     "Never stop an antibiotic course early even if you feel better. Incomplete courses allow resistant bacteria to survive. Never take antibiotics for viral infections like the common cold. Always use antibiotics only when prescribed."),
    ("Medicine Storage",
     "Most medicines should be stored below 25°C away from direct sunlight and moisture. Insulin and some liquid antibiotics need refrigeration (2–8°C). Check the label. Never store medicines in the bathroom due to humidity."),
    ("Expiry Dates",
     "An expired medicine may be less effective or harmful. Never use expired medicines. Safe disposal: return to pharmacy for proper waste disposal; do not flush or throw in household waste."),
    ("Paracetamol Safety",
     "Paracetamol is safe at recommended doses but the maximum adult dose is 4 g per day (4000 mg). Many combination cold/flu medicines already contain Paracetamol — double-check before taking extra doses to avoid liver damage."),
    ("Diabetes Medicine Guide",
     "Metformin is the first-line oral medicine for Type 2 diabetes. Always take with food to reduce GI side effects. Never skip doses. Monitor blood sugar regularly. SGLT2 inhibitors (Dapagliflozin) and DPP-4 inhibitors (Sitagliptin) are add-ons. Insulin is used when oral agents are insufficient."),
    ("Blood Pressure Medicines",
     "ACE Inhibitors (Ramipril) and ARBs (Losartan) protect kidneys in diabetics. Amlodipine (calcium channel blocker) and Metoprolol (beta blocker) are also first-line. Take BP medicines at the same time daily. Never stop without medical advice — rebound hypertension is dangerous."),
    ("Thyroid Medicine Tips",
     "Levothyroxine (T4) must be taken on an empty stomach, 30–60 minutes before breakfast, at the same time every day. Many supplements (calcium, iron, soya) reduce absorption. TSH blood test monitors adequacy every 6–12 months."),
    ("Pain Reliever Guide",
     "Paracetamol is the safest first-choice painkiller for most people. NSAIDs (Ibuprofen, Diclofenac) are more powerful for inflammation but risk GI irritation — always take after food. Aspirin has antiplatelet effects so avoid for simple pain if on blood thinners."),
    ("Allergy Medicines",
     "First-generation antihistamines (Chlorphenamine) cause significant drowsiness. Second-generation (Cetirizine, Loratadine, Fexofenadine) are preferred for daytime use. Avoid alcohol with antihistamines. Intranasal corticosteroids (Mometasone) are gold standard for allergic rhinitis."),
    ("Vitamin and Supplement Safety",
     "Vitamins are not always harmless at high doses. Fat-soluble vitamins (A, D, E, K) accumulate and can be toxic. Vitamin D > 4000 IU/day long-term needs monitoring. Always get blood levels checked before starting high-dose supplementation."),
    ("Pharmacy Safety Tips",
     "Always check: 1) Your name on the label 2) Medicine name and dose 3) Expiry date 4) Number of tablets. Ask the pharmacist to explain usage if unclear. Keep a medicine list for all household members. Keep medicines out of children's reach."),
]

# ── Symptom → medicine quick reference ───────────────────────────────────────
SYMPTOMS: list[dict] = [
    {"symptom": "Fever", "otc": "Paracetamol 500–1000 mg every 6 h", "warning": "Seek doctor if > 38.5°C for > 3 days or in children under 3 months."},
    {"symptom": "Headache", "otc": "Paracetamol 500 mg or Ibuprofen 400 mg after food", "warning": "Sudden severe headache ('thunderclap') = emergency."},
    {"symptom": "Common cold / runny nose", "otc": "Cetirizine 10 mg + saline nasal drops; rest and fluids", "warning": "Antibiotics do NOT work for viral colds."},
    {"symptom": "Heartburn / acidity", "otc": "Omeprazole 20 mg before food OR antacid gel", "warning": "If swallowing difficulty or blood in stool — seek urgent care."},
    {"symptom": "Mild allergy / hives", "otc": "Cetirizine 10 mg once daily", "warning": "Anaphylaxis (throat swelling, difficulty breathing) = EMERGENCY — call 108."},
    {"symptom": "Muscle / joint pain", "otc": "Ibuprofen 400 mg after food; Diclofenac gel topically", "warning": "Avoid NSAIDs if on blood thinners or with kidney disease."},
    {"symptom": "Diarrhoea", "otc": "ORS (Oral Rehydration Salts) + Zinc 20 mg; Loperamide for adults only", "warning": "Blood in stool or high fever → consult doctor."},
    {"symptom": "Constipation", "otc": "Isabgol (Psyllium husk) with water; Lactulose syrup", "warning": "Sudden change in bowel habits lasting > 3 weeks → GP review."},
]
