# -*- coding: utf-8 -*-
"""
AVPU — Alpaben Vipulbhai Patel University
Static knowledge base: programs, placement companies, and tutor knowledge chunks.
Kept in-code (no DB needed) so the app runs anywhere; indexed by rag.py.
"""

# ── Academic programs (used by Smart Admissions + program explorer) ──────────
PROGRAMS = [
    {
        "code": "btech-cse", "name": "B.Tech — Computer Science & Engineering", "level": "Undergraduate",
        "duration": "4 years", "fees": "₹95,000 / year",
        "eligibility": "10+2 with Physics, Maths & 50%+",
        "skills": ["Programming", "Data Structures", "Algorithms", "DBMS", "Operating Systems", "Web Development"],
        "careers": ["Software Engineer", "Backend Developer", "Full-Stack Developer", "SDE"],
        "desc": "Core computer science with strong software engineering, systems and full-stack development, plus AI electives.",
    },
    {
        "code": "btech-aiml", "name": "B.Tech — Artificial Intelligence & Machine Learning", "level": "Undergraduate",
        "duration": "4 years", "fees": "₹1,10,000 / year",
        "eligibility": "10+2 with Physics, Maths & 50%+",
        "skills": ["Python", "Machine Learning", "Deep Learning", "NLP", "Computer Vision", "MLOps"],
        "careers": ["AI Engineer", "ML Engineer", "Data Scientist", "Applied Scientist"],
        "desc": "A future-ready degree focused on machine learning, deep learning, NLP, computer vision and deploying AI systems.",
    },
    {
        "code": "btech-data", "name": "B.Tech — Data Science", "level": "Undergraduate",
        "duration": "4 years", "fees": "₹1,05,000 / year",
        "eligibility": "10+2 with Maths & 50%+",
        "skills": ["Statistics", "Python", "SQL", "Data Visualization", "Machine Learning", "Big Data"],
        "careers": ["Data Analyst", "Data Scientist", "BI Analyst", "Data Engineer"],
        "desc": "Turn data into decisions with statistics, analytics, ML and large-scale data engineering.",
    },
    {
        "code": "bca", "name": "BCA — Bachelor of Computer Applications", "level": "Undergraduate",
        "duration": "3 years", "fees": "₹55,000 / year",
        "eligibility": "10+2 in any stream with 50%+",
        "skills": ["Programming", "Web Development", "DBMS", "Software Testing", "Cloud Basics"],
        "careers": ["Web Developer", "Junior Developer", "QA Engineer", "IT Support"],
        "desc": "A practical software applications degree covering web, databases and modern development for quick industry entry.",
    },
    {
        "code": "mca", "name": "MCA — Master of Computer Applications", "level": "Postgraduate",
        "duration": "2 years", "fees": "₹85,000 / year",
        "eligibility": "Bachelor's with Maths / BCA / B.Sc IT",
        "skills": ["Advanced Programming", "System Design", "Cloud", "DevOps", "AI Foundations"],
        "careers": ["Software Engineer", "System Analyst", "Cloud Engineer", "Tech Lead"],
        "desc": "An advanced computing master's for software architecture, cloud, DevOps and AI-enabled applications.",
    },
    {
        "code": "msc-ai", "name": "M.Sc — Artificial Intelligence & Machine Learning", "level": "Postgraduate",
        "duration": "2 years", "fees": "₹95,000 / year",
        "eligibility": "Bachelor's in CS / IT / Maths / related",
        "skills": ["Machine Learning", "Deep Learning", "Generative AI", "LLMs", "RAG", "Research"],
        "careers": ["AI Engineer", "ML Researcher", "NLP Engineer", "Applied Scientist"],
        "desc": "Deep specialization in modern AI — generative models, LLMs, RAG and applied research projects.",
    },
    {
        "code": "mba-btech", "name": "MBA — Business Analytics", "level": "Postgraduate",
        "duration": "2 years", "fees": "₹1,20,000 / year",
        "eligibility": "Bachelor's in any discipline",
        "skills": ["Analytics", "Business Strategy", "SQL", "Visualization", "Product Thinking", "Leadership"],
        "careers": ["Business Analyst", "Product Manager", "Consultant", "Analytics Manager"],
        "desc": "Blend management with data — analytics, strategy and product thinking for data-driven leadership roles.",
    },
    {
        "code": "diploma-fullstack", "name": "PG Diploma — Full-Stack Development", "level": "Diploma",
        "duration": "1 year", "fees": "₹65,000",
        "eligibility": "Any graduate / final-year student",
        "skills": ["JavaScript", "React", "Node.js", "FastAPI", "Databases", "Deployment"],
        "careers": ["Full-Stack Developer", "Frontend Developer", "Backend Developer"],
        "desc": "An intensive, project-first diploma that makes you job-ready as a full-stack developer in a year.",
    },
    {
        "code": "diploma-genai", "name": "PG Diploma — Generative AI & LLM Apps", "level": "Diploma",
        "duration": "1 year", "fees": "₹75,000",
        "eligibility": "Any graduate with basic programming",
        "skills": ["Python", "LLMs", "Prompt Engineering", "RAG", "LangGraph", "AI App Deployment"],
        "careers": ["AI Application Developer", "LLM Engineer", "AI Product Builder"],
        "desc": "Build and ship real LLM products — agents, RAG pipelines and AI apps — in one focused year.",
    },
    {
        "code": "diploma-datasci", "name": "PG Diploma — Data Science & Analytics", "level": "Diploma",
        "duration": "1 year", "fees": "₹70,000",
        "eligibility": "Any graduate",
        "skills": ["Python", "Pandas", "SQL", "Statistics", "Machine Learning", "Power BI"],
        "careers": ["Data Analyst", "Junior Data Scientist", "BI Analyst"],
        "desc": "Hands-on analytics and machine learning to launch a data career fast.",
    },
    {
        "code": "btech-ece", "name": "B.Tech — Electronics & Communication", "level": "Undergraduate",
        "duration": "4 years", "fees": "₹90,000 / year",
        "eligibility": "10+2 with Physics, Maths & 50%+",
        "skills": ["Embedded Systems", "IoT", "Signal Processing", "VLSI", "Communication"],
        "careers": ["Embedded Engineer", "IoT Developer", "Hardware Engineer"],
        "desc": "Electronics, embedded systems and IoT with a bridge into AI-on-the-edge applications.",
    },
    {
        "code": "bsc-it", "name": "B.Sc — Information Technology", "level": "Undergraduate",
        "duration": "3 years", "fees": "₹50,000 / year",
        "eligibility": "10+2 in any stream with 45%+",
        "skills": ["Programming", "Networking", "Databases", "Web Basics", "Cybersecurity Basics"],
        "careers": ["IT Executive", "Junior Developer", "Support Engineer"],
        "desc": "A broad IT foundation covering programming, networks, databases and security fundamentals.",
    },
    {
        "code": "cert-cyber", "name": "Certificate — Cybersecurity Essentials", "level": "Certificate",
        "duration": "6 months", "fees": "₹35,000",
        "eligibility": "Any student / working professional",
        "skills": ["Network Security", "Ethical Hacking", "OWASP", "SOC Basics"],
        "careers": ["Security Analyst (Entry)", "SOC Analyst"],
        "desc": "A short, practical entry into cybersecurity and defensive security operations.",
    },
    {
        "code": "cert-cloud", "name": "Certificate — Cloud & DevOps", "level": "Certificate",
        "duration": "6 months", "fees": "₹40,000",
        "eligibility": "Any student with basic programming",
        "skills": ["Linux", "Docker", "CI/CD", "AWS Basics", "Kubernetes Basics"],
        "careers": ["DevOps Trainee", "Cloud Support Engineer"],
        "desc": "Get hands-on with containers, CI/CD and cloud to start a DevOps career.",
    },
]


# ── Placement partner companies (used by AI Placement Matcher) ───────────────
COMPANIES = [
    {"name": "Tatvasoft", "sector": "Software Services", "city": "Ahmedabad",
     "roles": ["Software Engineer", "Full-Stack Developer"], "skills": ["C#", ".NET", "JavaScript", "SQL", "React"]},
    {"name": "Bacancy Technology", "sector": "Software / AI", "city": "Ahmedabad",
     "roles": ["AI Engineer", "Node.js Developer", "React Developer"], "skills": ["Python", "Node.js", "React", "Machine Learning", "AWS"]},
    {"name": "Rapidops", "sector": "Product / SaaS", "city": "Ahmedabad",
     "roles": ["Software Engineer", "Data Engineer"], "skills": ["Java", "Python", "SQL", "AWS", "Data Engineering"]},
    {"name": "Space-O Technologies", "sector": "Mobile / Software", "city": "Ahmedabad",
     "roles": ["Mobile Developer", "Backend Developer"], "skills": ["Swift", "Kotlin", "Node.js", "MongoDB"]},
    {"name": "CMARIX TechnoLabs", "sector": "Web / Enterprise", "city": "Ahmedabad",
     "roles": ["Full-Stack Developer", "PHP Developer"], "skills": ["PHP", "Laravel", "JavaScript", "MySQL", "React"]},
    {"name": "Zignuts Technolab", "sector": "Software / AI", "city": "Gandhinagar",
     "roles": ["AI Engineer", "Full-Stack Developer"], "skills": ["Python", "Node.js", "React", "LLMs", "MongoDB"]},
    {"name": "TOPS Infosolutions", "sector": "Software Services", "city": "Ahmedabad",
     "roles": ["Software Engineer", "QA Engineer"], "skills": ["Java", "Python", "Selenium", "SQL"]},
    {"name": "ESparkBiz", "sector": "Software / Cloud", "city": "Ahmedabad",
     "roles": ["Cloud Engineer", "Full-Stack Developer"], "skills": ["AWS", "Docker", "Node.js", "React", "DevOps"]},
    {"name": "Infostretch (Apexon)", "sector": "Digital Engineering", "city": "Ahmedabad",
     "roles": ["Data Scientist", "Automation Engineer"], "skills": ["Python", "Machine Learning", "Selenium", "AWS", "SQL"]},
    {"name": "Simform", "sector": "Product Engineering", "city": "Ahmedabad",
     "roles": ["Full-Stack Developer", "Cloud Engineer"], "skills": ["React", "Node.js", "AWS", "Python", "Microservices"]},
    {"name": "Yudiz Solutions", "sector": "Apps / Games / AI", "city": "Ahmedabad",
     "roles": ["AI Developer", "Mobile Developer"], "skills": ["Python", "Machine Learning", "Unity", "Flutter"]},
    {"name": "Silver Touch Technologies", "sector": "Enterprise IT", "city": "Ahmedabad",
     "roles": ["Software Engineer", "Data Analyst"], "skills": ["Java", "SQL", "Power BI", "SAP"]},
    {"name": "Volansys (ACL Digital)", "sector": "Embedded / IoT", "city": "Ahmedabad",
     "roles": ["Embedded Engineer", "IoT Developer"], "skills": ["C", "C++", "Embedded", "IoT", "Python"]},
    {"name": "Aubergine Solutions", "sector": "Product / Design", "city": "Ahmedabad",
     "roles": ["Full-Stack Developer", "Backend Developer"], "skills": ["Python", "Django", "React", "PostgreSQL"]},
    {"name": "Softqube Technologies", "sector": "Web / Mobile", "city": "Ahmedabad",
     "roles": ["Web Developer", "App Developer"], "skills": ["PHP", "JavaScript", "React Native", "MySQL"]},
    {"name": "Weblineindia", "sector": "Software Services", "city": "Ahmedabad",
     "roles": ["Software Engineer", "AI Developer"], "skills": ["Python", "Machine Learning", "Node.js", "React"]},
    {"name": "Elsner Technologies", "sector": "Web / E-commerce", "city": "Ahmedabad",
     "roles": ["Full-Stack Developer", "Shopify Developer"], "skills": ["JavaScript", "React", "Node.js", "Shopify"]},
    {"name": "Kody Technolab", "sector": "AI / Mobile", "city": "Ahmedabad",
     "roles": ["AI Engineer", "Flutter Developer"], "skills": ["Python", "Machine Learning", "Flutter", "TensorFlow"]},
    {"name": "Radixweb", "sector": "Software / Cloud", "city": "Ahmedabad",
     "roles": ["Software Engineer", "Cloud Engineer"], "skills": ["Java", ".NET", "Azure", "SQL", "Angular"]},
    {"name": "InfoStride", "sector": "Data / AI", "city": "Gandhinagar",
     "roles": ["Data Scientist", "Data Analyst"], "skills": ["Python", "SQL", "Machine Learning", "Power BI", "Statistics"]},
]


# ── Tutor knowledge base (grounds the AI Tutor via RAG) ──────────────────────
# Mix of AVPU facts + core CS/AI study concepts.
KNOWLEDGE = [
    ("AVPU Admissions", "AVPU admissions open twice a year (July and January intakes). Apply online with your 10+2 or graduation marksheet. Merit and entrance-based seats are available, plus scholarships through the AVP Charitable Trust."),
    ("AVPU Scholarships", "AVPU offers merit-based scholarships (up to 50% tuition for top scorers) and need-based scholarships via the AVP Charitable Trust. Sports and first-generation-learner scholarships are also available."),
    ("AVPU Placements", "AVPU runs a dedicated placement cell with 20+ hiring partners across Ahmedabad and Gandhinagar. Students get mock interviews, ATS resume reviews and an AI placement matcher. Average package for AI/CS graduates targets ₹4-8 LPA."),
    ("AVPU Campus", "The AVPU campus includes AI and data-science labs, a research & innovation center, a 24/7 library, high-speed internet, hostels and sports facilities. Every student gets a personal AI tutor account."),
    ("AVPU Fees & EMI", "Fees vary by program (₹35,000 for certificates up to ₹1,20,000/year for MBA). Semester-wise payment and no-cost EMI options are available, plus scholarships to reduce the burden."),
    ("Python Basics", "Python is a beginner-friendly, high-level language. Key building blocks: variables, data types (int, float, str, list, dict), loops (for/while), functions (def), and modules. It is the primary language for AI and data science."),
    ("Data Structures", "Core data structures include arrays/lists, stacks (LIFO), queues (FIFO), linked lists, hash maps (dictionaries), trees and graphs. Choosing the right structure affects time and space complexity."),
    ("Algorithms & Big-O", "Big-O notation describes how an algorithm scales. O(1) constant, O(log n) logarithmic (binary search), O(n) linear, O(n log n) good sorts (merge/quick), O(n^2) nested loops. Aim for lower complexity on large inputs."),
    ("DBMS & SQL", "A database stores structured data in tables. SQL is used to query it: SELECT columns FROM table WHERE condition. Joins combine tables; indexes speed up reads; normalization reduces redundancy."),
    ("Machine Learning", "Machine learning learns patterns from avpu_data. Supervised learning (labelled data) covers regression and classification; unsupervised learning finds structure (clustering). Split data into train/test and evaluate with accuracy, precision, recall."),
    ("Deep Learning", "Deep learning uses neural networks with many layers. CNNs excel at images, RNNs/Transformers at sequences and text. Training adjusts weights via backpropagation and gradient descent to minimize a loss function."),
    ("Natural Language Processing", "NLP lets computers work with human language: tokenization, embeddings, sentiment analysis, named-entity recognition and text generation. Modern NLP is powered by transformer models and large language models (LLMs)."),
    ("Large Language Models", "LLMs like GPT and LLaMA are transformer models trained on huge text corpora. They predict the next token to generate text. Techniques like RAG (retrieval-augmented generation) ground them in your own documents to reduce hallucination."),
    ("RAG Pipelines", "Retrieval-Augmented Generation retrieves relevant documents from a vector database, then feeds them to an LLM as context. This grounds answers in real data. Steps: chunk documents, embed them, store vectors, retrieve top-k, generate an answer."),
    ("Web Development", "Frontend (HTML, CSS, JavaScript, React) builds what users see; backend (FastAPI, Node.js) handles logic and data; databases store information. REST APIs connect frontend and backend using HTTP methods (GET, POST)."),
    ("Version Control (Git)", "Git tracks changes to code. Core commands: git clone, git add, git commit, git push, git pull, and branches for parallel work. GitHub hosts repositories and enables collaboration through pull requests."),
    ("Operating Systems", "An OS manages hardware and software: processes and threads, CPU scheduling, memory management (paging), file systems and concurrency. Understanding these helps you write efficient programs."),
    ("Interview Preparation", "For tech interviews, practice data structures & algorithms, system design basics, and be ready to explain your projects. Use the STAR method for behavioural questions and always ask clarifying questions in coding rounds."),
    ("Statistics for Data Science", "Key ideas: mean, median, variance, standard deviation, probability distributions, correlation vs causation, and hypothesis testing. Statistics underpins every data science and machine-learning decision."),
    ("Cloud Computing", "Cloud platforms (AWS, Azure, GCP) provide on-demand compute, storage and services. Core concepts: virtual machines, containers (Docker), object storage, and serverless functions. DevOps automates deployment with CI/CD."),
]
